In [1]:
import numpy as np

In [5]:
arr = np.array([[1,5,8],[9,5,3]])
arr

array([[1, 5, 8],
       [9, 5, 3]])

In [6]:
np.sum(arr,axis=1)

array([14, 17])

In [7]:
np.sum(arr,axis=0)

array([10, 10, 11])