# NumPy

In [36]:
import numpy as np

In [37]:
# create 1d array
arr = np.array([1,2,3,4,5])
print(arr, type(arr))
print(arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)


In [16]:
reshaped_arr = arr.reshape(1,5)
print(reshaped_arr)
print(reshaped_arr.shape)

[[1 2 3 4 5]]
(1, 5)


In [17]:
# create 2d array
arr = np.array([[1,2,3],[6,5,3]])
print(arr)
print(arr.shape)

[[1 2 3]
 [6 5 3]]
(2, 3)


In [22]:
# arange()
arr = np.arange(0,11,2)
print(arr)
print(arr.shape)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)
print(reshaped_arr.shape)

[ 0  2  4  6  8 10]
(6,)
[[ 0  2]
 [ 4  6]
 [ 8 10]]
(3, 2)


In [ ]:
# linspace()
arr = np.linspace(0,10,5) # return evenly spaced numbers over a specified interval.
print(arr)
print(arr.shape)

[ 0.   2.5  5.   7.5 10. ]


In [32]:
# ones()
arr = np.ones(5)
print("arr =\n",arr)
arr = np.ones(5,dtype=int)
print("arr =\n",arr)
arr = np.ones((2,3))
print("arr =\n",arr)

arr =
 [1. 1. 1. 1. 1.]
arr =
 [1 1 1 1 1]
arr =
 [[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
# zeros()
arr = np.zeros(5)
print("arr =\n",arr)
arr = np.zeros(5,dtype=int)
print("arr =\n",arr)
arr = np.zeros((2,3))
print("arr =\n",arr)

arr =
 [0. 0. 0. 0. 0.]
arr =
 [0 0 0 0 0]
arr =
 [[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# identity matrix
mat = np.eye(3)
print(mat)
mat = np.eye(3, dtype=int)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# some imp. attributes of numpy array
# arr.shape
# arr.ndim
# arr.size
# arr.dtype
# arr.itemsize

In [ ]:
arr = np.array([[1,2,3],[9,5,3]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize) # in bytes

[[1 2 3]
 [9 5 3]]
(2, 3)
2
int64
8


In [42]:
# numpy vectorized operation
arr1 = np.array([10,5,9,8,3])
arr2 = np.array([3,6,4,3,5])

# element wise addition
print(arr1+arr2)
# element wise substraction
print(arr1-arr2)
# element wise multiplication
print(arr1*arr2)
# element wise division
print(arr1/arr2)

[13 11 13 11  8]
[ 7 -1  5  5 -2]
[30 30 36 24 15]
[3.33333333 0.83333333 2.25       2.66666667 0.6       ]


In [43]:
# universal functions
arr = np.array([1,2,3,4,5])
# sqrt func
print(np.sqrt(arr))
# exp func
print(np.exp(arr))
# sin func
print(np.sin(arr))
# natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [50]:
## array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array =\n",arr)

# indexing
print(arr[1][1]) # 5
# slicing
print(arr[1:,1:])
print(arr[:2,1:])
# modify
arr[0][0] = 0
print("arr =\n",arr)
arr[1:] = 1
print("arr =\n",arr)

array =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[[5 6]
 [8 9]]
[[2 3]
 [5 6]]
arr =
 [[0 2 3]
 [4 5 6]
 [7 8 9]]
arr =
 [[0 2 3]
 [1 1 1]
 [1 1 1]]


#### Practical Examples

In [54]:
# normalisation (a statistical concept): to have mean = 0 & standard deviation = 1
data = np.array([1,2,3,4,5])
# mean & standard deviation
mn = np.mean(data)
std_dev = np.std(data)
# normalise the data
norm_data = (data-mn)/std_dev
print('normalised data:',norm_data)

normalised data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [56]:
lt = list(range(1,11))
lt

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
data = np.array(range(1,11))
print('data =',data)
# mean
mn = np.mean(data)
print('mean =',mn)
# median
med = np.median(data)
print('median =',med)
# standard deviation
std_dev = np.std(data)
print('standard deviation =',std_dev)
# variance
variance = np.var(data)
print('variance =',variance)

data = [ 1  2  3  4  5  6  7  8  9 10]
mean = 5.5
median = 5.5
standard deviation = 2.8722813232690143
variance = 8.25


In [71]:
# logical operation
data = np.array(range(1,11))
print('data =',data)
print(data>5) # [False False False False False  True  True  True  True  True]
print(data[data>5])
print(data[(data>=3) & (data<=6)])

data = [ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[3 4 5 6]
